### ISSUE TITLE
FOUC issue

### ISSUE THREAD

**Issue by Barbapapazes** [adonisjs/vite#10]
### Package version

3.0.0-8

### Describe the bug

Hello,

I'm using Tailwind CSS and Unpoly. I'm loading my CSS from the `app.js` file but because of that, the CSS can only load once the TS is loaded.

1. Clone the reproduction
2. Start the server
3. Open the browser and observe the FOUC

### Reproduction repo

https://github.com/Barbapapazes/adonis-vite-fouc

**Comment by Julien-R44** [comment]
thanks man
i'm working right now on a fix for FOUC when CSS is imported via Javascript

but as I said in #8, in your case the resolution is simple, just make a specific entrypoint for your CSS `@vite(['resources/js/app.js, 'resources/css/app.css'])`

**Comment by Barbapapazes** [comment]
> thanks man i'm working right now on a fix for FOUC when CSS is imported via Javascript
> 
> but as I said in #8, in your case the resolution is simple, just make a specific entrypoint for your CSS `@vite(['resources/js/app.js, 'resources/css/app.css'])`

Yes but the imported CSS in the TS file comes after the local CSS files which could be an issue.

And I raised this issue because you say in your guide that this is the recommended way to do!

**Comment by Julien-R44** [comment]
New release has been published. Let me know if it work for you https://github.com/adonisjs/vite/releases/tag/v3.0.0-9

**Comment by Barbapapazes** [comment]
Yes, this is solved! Thanks man!
