### ISSUE TITLE
Vite overwrite the `Access-Control-Allow-Origin` from the CORS module 

### ISSUE THREAD

**Issue by Barbapapazes** [adonisjs/vite#13]
### Package version

3.0.0-8

### Describe the bug

Hello,

I'm using the CORS module this the setting `origin` to `true`. In the same time, I'm fetching my server, from another domain, with the `withCredentials` to true. The browser use a preflight request but the server return `*` instead of the domain that fetch the server. This cause an issue because it's forbidden.

similar to o https://github.com/nuxt/nuxt/issues/23962

**Comment by Julien-R44** [comment]
Should be resolved with https://github.com/adonisjs/vite/pull/14 and so version 3.0.0-11 !

But beware, we have a breaking change, see https://github.com/adonisjs/vite/releases/tag/v3.0.0-11
