### ISSUE TITLE
Can we have preloaded assets support like Laravel

### ISSUE THREAD

**Issue by irshadahmad21** [adonisjs/vite#6]
### Package version

3.0.0-2

### Describe the bug

Laravel provides `AddLinkHeadersForPreloadedAssets` middleware which [preloads assets](https://github.com/laravel/framework/blob/7c680bb58dfb15923209045f99ed5cf46c31f45d/src/Illuminate/Http/Middleware/AddLinkHeadersForPreloadedAssets.php#L20-L24) which are generated while [parsing the entrypoints](https://github.com/laravel/framework/blob/7c680bb58dfb15923209045f99ed5cf46c31f45d/src/Illuminate/Foundation/Vite.php#L296-L367).

This preloading is importing for dynamic assets/imports when using React or any other SSR builds.

Can we have the support for that?

**Comment by Julien-R44** [comment]
Gonna take a look. maybe it will come after version 3.x is released : i need to read a bit more about it.

however, thanks for pointing it out ! it will definitely be useful to have

**Comment by Julien-R44** [comment]
Implemented in 3.0.0-4
