### ISSUE TITLE
HMR is broken for React

### ISSUE THREAD

**Issue by muco-rolle** [adonisjs/vite#7]
### Package version

3.0.0-5

### Describe the bug

_See the attached video to get the context of the issue_ 

[Screencast from 2024-03-04 20-54-30.webm](https://github.com/adonisjs/vite/assets/43722815/2921e059-07b6-482d-8ec2-fa03c814dbb1)

And here's [the repo](https://github.com/muco-rolle/adonis-inertia-demo) for the reproduction of this issue

### Reproduction repo

https://github.com/muco-rolle/adonis-inertia-demo

**Comment by Julien-R44** [comment]
Hey

add this to your `adonisrc.ts`

```ts
import { defineConfig } from '@adonisjs/core/app'

export default defineConfig({
  assetsBundler: false,
  unstable_assembler: {
    onBuildStarting: [() => import('@adonisjs/vite/build_hook')],
  },
})
```

and also this to your root tsconfig : 

```json
  "exclude": ["./resources/**/*"]
```

and you should be good. 
This repo can be used as a reference : https://github.com/adonisjs/inertia-starter-kit 

Wait a few days for the official release and documentation that will explains that

Feel free to reopen if issue persists

**Comment by muco-rolle** [comment]
It works. Thanks!
